#!/usr/bin/env ruby
require "clint"

path = ARGV[0]
exts = Clint::Linter.new(path).gems_with_extensions_list

unless exts.empty?
  exts.each do |ext|
    puts "C Extension found in: #{ext}"
  end
else
  puts "No C extensions found"
end
